### PR TITLE
moved blocks? to utilities

### LINKED ISSUE #29: Patch instructions
- [ ] The second argument of `cmpq` must not be an immediate value (e.g. `cmpq $1 $2` is not allowed). `patch-instructions` should turn that into something like: `movq $2 %rax; cmpq $1 %rax`
- [ ] The second argument of `movzbq` must be a register. 
- [ ] Figure out what to do with `jmp-if`, `jmp`

### PR DESCRIPTION
**Pull request by mfekadu**
resolves #29 and #30 and #42 and #35

### CODE REVIEW

**Comment by mfekadu** [comment]
**This was an interesting assembly error because patch-instr put the whole prog into the asm file haha**
```bash
> ./run programs/if-should-exit-42.rc
programs/if-should-exit-42.s:1:1: error: single quote way too long
'(program () ((block () (label block1328) (movq (int 42) (reg rax)) (jmp conclusion)) (block () (label block1329) (movq (int 44) (reg rax)) (jmp conclusion)) (block () (label block1330) (cmpq (reg rbx) (int 1)) (jmp-if e block1328) (jmp block1329)) (block () (label block1331) (movq (int 0) (reg rbx)) (jmp block1330)) (block () (label block1332) (cmpq (int 2) (int 1)) (set e (byte-reg al)) (movzbq (byte-reg al) (reg rbx)) (cmpq (int 0) (reg rbx)) (set e (byte-reg al)) (movzbq (byte-reg al) (reg rbx)) (jmp block1330)) (block () (label start) (cmpq (int 2) (int 1)) (set l (byte-reg al)) (movzbq (byte-reg al) (reg rbx)) (cmpq (reg rbx) (int 1)) (jmp-if e block1331) (jmp block1332))))
^
programs/if-should-exit-42.s:1:1: error: unexpected token at start of statement
'(program () ((block () (label block1328) (movq (int 42) (reg rax)) (jmp conclusion)) (block () (label block1329) (movq (int 44) (reg rax)) (jmp conclusion)) (block () (label block1330) (cmpq (reg rbx) (int 1)) (jmp-if e block1328) (jmp block1329)) (block () (label block1331) (movq (int 0) (reg rbx)) (jmp block1330)) (block () (label block1332) (cmpq (int 2) (int 1)) (set e (byte-reg al)) (movzbq (byte-reg al) (reg rbx)) (cmpq (int 0) (reg rbx)) (set e (byte-reg al)) (movzbq (byte-reg al) (reg rbx)) (jmp block1330)) (block () (label start) (cmpq (int 2) (int 1)) (set l (byte-reg al)) (movzbq (byte-reg al) (reg rbx)) (cmpq (reg rbx) (int 1)) (jmp-if e block1331) (jmp block1332))))
^
18
>
```

**Comment by mfekadu** [comment]
**NICE**
```
> ./run programs/if-should-exit-42.rc
42
> ./run programs/test-spill-regs-should-exit-18.rc
18
>
```

**Comment by mfekadu** [comment]
#35 
```
> ./run programs/test-should-exit-code-4.rc
4
>
```

**Comment by johnvtan** [comment]
:fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: 
      :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: 
:fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: 
      :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: 
:fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: 
      :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: 
:fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire:

**Pull request merged**
