### PR TITLE
delete all rust source code 🦀💀😢

### PR DESCRIPTION
**Pull request by mfekadu**

### CODE REVIEW

**Comment by mfekadu** [comment]
resolves #14

**Comment by johnvtan** [comment]
good. kill it with :fire:

**Review by johnvtan — APPROVED** [review]
:fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire:

**Comment by mfekadu** [comment]
The reasoning for switching to Racket is the answer to the following wise questions posed by some helpful people:
```
What are your long-term plans for the software? - Julian Squires
Why worry when a programming language is getting in the way of your art? - Christopher Ray Ertel
Ask yourself what you hope to get out of doing this project. - Lindsey Kuper
```
The long term plan for the software is to learn about how compilers work because the important details of that concept do not rely on the implementation details of Rust. For example, [Lindsey Kuper's blog post](https://blog.sigplan.org/2019/07/09/my-first-fifteen-compilers/) opened my eyes to how the few passes completed so far have been compilers themselves. That important detail is tremendously motivating!

On top of that: It was not too much code to rewrite, and the rewrite was quick thanks to Racket's fast development workflow. 


I suppose some other reasons:
* the textbook uses Racket
* Racket is designed for parsers/interpreters/compilers
* [Self-compiling](https://www.sigbus.info/how-i-wrote-a-self-hosting-c-compiler-in-40-days) sounds like a fun idea

**Pull request merged**
